# 基础配置
title: "阿利亚的技术博客"
description: "微信/百度/贴吧/ 号【购 g.h17b.cc买】抖音/快手/知乎/QQ/58/头条/支付宝/淘宝/千牛闲鱼/拼多多商店/
/Facebook/whatsapp/twitter推特/谷歌邮箱Gmail/tiktok运营技术伦理探究。"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 永久链接格式
permalink: /:year/:month/:day/:title/

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
