# 基础配置
url: "https://aliya981.github.io"
baseurl: ""
title: "阿利亚的技术博客"
description: "微信/百度/贴吧/ 【罔 g点h17b点cc址】抖音/快手/知乎/QQ/58/头条/支付宝/淘宝/千牛闲鱼/拼多多商店/ /Facebook/whatsapp/twitter推特/谷歌邮箱Gmail/tiktok分享运营、GitHub 技巧与科技伦理思考"
author: "aliya981"

# 插件配置（GitHub Pages 兼容）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# 默认配置
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 搜索引擎验证
meta_tags:
  google-site-verification: "YutoUnqDeeG665BQdq1eXjcjTn0kBR1Kgea4S4nbtdg"
  msvalidate.01: "7BE6EBA07CFE1F875A642F103A710464"

# Sitemap配置
sitemap:
  # 包含的文件类型
  filetypes:
    - html
    - xml
    - pdf
  # 排除的文件/目录
  exclude:
    - "/404.html"
    - "/assets/"
    - "/images/"
  # 修改频率
  changefreq: "weekly"
  # 优先级
  priority: 0.8

# 社交媒体链接（可选配置）
social:
  wechat: "g.h17b.cc"
  github: "aliya981"
  twitter: "#"
  facebook: "#"
  whatsapp: "#"
