# 基础配置
url: "https://aliya981.github.io"
baseurl: ""

# 插件配置（GitHub Pages 兼容）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap  # 自动生成 sitemap.xml

# 搜索引擎验证（合并到一个 meta_tags 块）
meta_tags:
  google-site-verification: "你的Google验证码（仅数字部分）"  # 示例：AbCdE12345
  msvalidate.01: "你的Bing验证码（完整字符串）"             # 示例：ABCDEF1234567890ABCDEF1234567890
