# 必须配置
url: "https://aliya981.github.io"
baseurl: ""  # 如果是项目站点，保持为空

# 插件白名单（GitHub Pages仅支持这些）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# 示例（替换 YOUR_VERIFICATION_CODE）
meta_tags:
  verification: <meta name="msvalidate.01" content="YOUR_VERIFICATION_CODE" />
  plugins:
  - jekyll-sitemap  # 自动生成兼容Google和Bing的sitemap.xml
meta_tags:
  google-site-verification: "你的Google验证码"
  meta_tags:
  msvalidate.01: "你的Bing验证码"
